In [39]:
from tensorflow.keras.preprocessing.text import one_hot

In [41]:
sent=['the glass of milk',
'the cup of tea',
'i am a good developer',
'your videos are good',
'i am a good boy']

In [43]:
## Define vocab size
voc_size = 10000

In [67]:
## One hot representation
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep

[[4069, 6858, 423, 8008],
 [4069, 1861, 423, 2342],
 [9910, 2898, 2599, 9318, 299],
 [2863, 415, 2725, 9318],
 [9910, 2898, 2599, 9318, 3001]]

In [69]:
## word embedding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [49]:
import numpy as np

In [51]:
##  transforms a list (of length `num_samples`) of sequences (lists of integers) into a 2D NumPy array
sent_length = 8
embedded_docs = pad_sequences(one_hot_rep, padding='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 4069 6858  423 8008]
 [   0    0    0    0 4069 1861  423 2342]
 [   0    0    0 9910 2898 2599 9318  299]
 [   0    0    0    0 2863  415 2725 9318]
 [   0    0    0 9910 2898 2599 9318 3001]]


In [53]:
## Feature representation 
dim = 10 

In [117]:
voc_size = 10000
model=Sequential()
model.add(Embedding(voc_size,dim))
model.compile('adam','mse')

In [119]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)              │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [121]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step


array([[[ 3.7620179e-03,  2.4775747e-02, -9.1113672e-03, -4.9880564e-02,
         -3.4529455e-03, -4.2473413e-02, -4.1672360e-02, -2.9445553e-02,
          3.1655915e-03,  3.2196011e-02],
        [ 3.7620179e-03,  2.4775747e-02, -9.1113672e-03, -4.9880564e-02,
         -3.4529455e-03, -4.2473413e-02, -4.1672360e-02, -2.9445553e-02,
          3.1655915e-03,  3.2196011e-02],
        [ 3.7620179e-03,  2.4775747e-02, -9.1113672e-03, -4.9880564e-02,
         -3.4529455e-03, -4.2473413e-02, -4.1672360e-02, -2.9445553e-02,
          3.1655915e-03,  3.2196011e-02],
        [ 3.7620179e-03,  2.4775747e-02, -9.1113672e-03, -4.9880564e-02,
         -3.4529455e-03, -4.2473413e-02, -4.1672360e-02, -2.9445553e-02,
          3.1655915e-03,  3.2196011e-02],
        [ 1.7279062e-02,  3.6905892e-03,  4.4131447e-02, -4.2245746e-02,
          4.7314279e-03,  2.8348971e-02, -4.5097984e-02, -4.9178779e-02,
         -4.2518105e-02, -3.5628401e-02],
        [ 8.3341822e-03, -4.6756793e-02, -3.8869966e-02, -4.

In [103]:
embedded_docs[0]

array([   0,    0,    0,    0, 4069, 6858,  423, 8008])